[workspace]

members = [
    "neutils",
    "examples/fair-queue-basic",    
    "examples/tun_device_sync",
    "examples/tun_device_async",
    "examples/async-fair-queue-basic",
]
exclude = ["testing/wasm-tests"]

resolver = "2"
